export const BLOGS = [
  {
    id: 'id',
    categoryId: 'categoryID',
    storeId: 'storeId',
    name: 'asasasas xoa bóp thảo dược đông yyyyyyyyCao xoa bóp thảo dược đông yyyyyyyyCao xoa bóp thảo dược đông yyyyyyyy xoa bóp thảo dược đông yyyyyyyy',
    description:
      'Amet minim mollit non deserunt ullamco est sit aliqua amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet Amet minim mollit non deserunt ullamco est sit aliqua amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet Amet minim mollit non deserunt ullamco est sit aliqua amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet',
    slug: 'slug',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_9-820x750.jpg'],
    tags: ['SỨC KHỎE', 'SỨC KHỎE'],
    createdAt: '11/11/2023',
    content: 'content',
  },
  {
    id: 'id2',
    categoryId:
      'categoryID2 categoryID2categoryID2categoryID2 categoryID2 categoryID2categoryID2 categoryID2categoryID2',
    storeId: 'storeId2',
    name: 'Các sản phẩm đang có chương trình khuyến mãi',
    description: 'description2',
    slug: 'slug2',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_9-820x750.jpg'],
    tags: ['KHUYẾN MÃI'],
    createdAt: '11/11/2023',
    content: 'content2',
  },
  {
    id: 'id',
    categoryId: 'categoryID',
    storeId: 'storeId',
    name: 'Mẹ bỉm sữa giảm mỡ bụng sau sinh',
    description: 'description',
    slug: 'slug',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_3-820x750.jpg'],
    tags: ['LÀM ĐẸP'],
    createdAt: '11/11/2023',
    content: 'content',
  },
  {
    id: 'id2',
    categoryId: 'categoryID2',
    storeId: 'storeId2',
    name: 'Nhang sạch thảo dược thiên nhiên không hóa chất',
    description: 'description2',
    slug: 'slug2',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_7-820x800.jpg'],
    tags: ['SỨC KHỎE'],
    createdAt: '11/11/2023',
    content: 'content2',
  },
  {
    id: 'id',
    categoryId: 'categoryID',
    storeId: 'storeId',
    name: 'Cao xoa bóp thảo dược đông y',
    description: 'description',
    slug: 'slug',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_2-820x801.jpg'],
    tags: ['SỨC KHỎE'],
    createdAt: '11/11/2023',
    content: 'content',
  },
  {
    id: 'id2',
    categoryId:
      'categoryID2 categoryID2categoryID2categoryID2 categoryID2 categoryID2categoryID2 categoryID2categoryID2',
    storeId: 'storeId2',
    name: 'Các sản phẩm đang có chương trình khuyến mãi',
    description: 'description2',
    slug: 'slug2',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_9-820x750.jpg'],
    tags: ['KHUYẾN MÃI'],
    createdAt: '11/11/2023',
    content: 'content2',
  },
  {
    id: 'id',
    categoryId: 'categoryID',
    storeId: 'storeId',
    name: 'Mẹ bỉm sữa giảm mỡ bụng sau sinh',
    description: 'description',
    slug: 'slug',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_3-820x750.jpg'],
    tags: ['LÀM ĐẸP'],
    createdAt: '11/11/2023',
    content: 'content',
  },
  {
    id: 'id2',
    categoryId: 'categoryID2',
    storeId: 'storeId2',
    name: 'Nhang sạch thảo dược thiên nhiên không hóa chất',
    description: 'description2',
    slug: 'slug2',
    images: ['https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_7-820x800.jpg'],
    tags: ['SỨC KHỎE'],
    createdAt: '11/11/2023',
    content: 'content2',
  },
];

export const POPULAR_TAGS = ['Beverage', 'HerbalTea', 'Hot Drink', 'Tea Culture'];

export const BLOG_CATEGORIES = ['Health & Nutrition', 'Lifestyle', 'Product Tips', 'Recipes'];

export const RECENT_POSTS = [
  {
    image: 'https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_9-150x150.jpg',
    title: 'Chamomile: Herbal Tea Of The Month',
    date: 'MAY 24, 2023',
  },
  {
    image: 'https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_3-150x150.jpg',
    title: '5 Personalities You Should Consider',
    date: 'MAY 23, 2023',
  },
  {
    image: 'https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_7-150x150.jpg',
    title: 'Fresh Coconut: Your Most Diuretic Infusion',
    date: 'MAY 22, 2023',
  },
  {
    image: 'https://demo2.wpopal.com/teapoz/wp-content/uploads/2023/05/blog_2-150x150.jpg',
    title: 'Immunity-Boosting To Add To Your Diet Now',
    date: 'MAY 19, 2023',
  },
];
